// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
dotenv.config();
import { defineConfig } from 'prisma/config';
import { IprepPaths } from '@iprep/shared/utils';

const connectionString = `file:${IprepPaths.dbFile}`;

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: connectionString,
  },
});
